In [1]:
import numpy as np
import pandas as pd

df=pd.read_csv('tmdb_movies_dataset.csv')

In [2]:
# df.info()
df.head()
# df.describe()
# df.isna().sum()

,id,title,original_title,overview,release_date,popularity,vote_average,vote_count,genre_ids,original_language
0,1087192,How to Train Your Dragon,How to Train Your Dragon,"On the rugged isle of Berk, where Vikings and ...",2025-06-06,1075.8358,8.126,1013,"[14, 10751, 28]",en
1,1071585,M3GAN 2.0,M3GAN 2.0,After the underlying tech for M3GAN is stolen ...,2025-06-25,828.4871,7.711,376,"[28, 878, 53]",en
2,1315986,Man with No Past,Man with No Past,"Waking up in an unfamiliar city, a man with no...",2025-01-13,510.3027,6.775,20,"[28, 18]",en
3,1011477,Karate Kid: Legends,Karate Kid: Legends,"After a family tragedy, kung fu prodigy Li Fon...",2025-05-08,368.2810,7.254,478,"[28, 12, 18]",en
4,1061474,Superman,Superman,"Superman, a journalist in Metropolis, embarks ...",2025-07-09,359.1730,7.500,961,"[878, 12, 28]",en

In [3]:
import ast

def preprocess_data(df):    
    # Imputation
    df['overview']=df['overview'].fillna('Unknown')

    # convert to DateTime
    df['release_date'] = pd.to_datetime(df['release_date'], errors='coerce')
    df['release_date']=df['release_date'].fillna(df['release_date'].median())
    # split 'release_date' into 'year', 'month', 'day'
    df['release_year'] = df['release_date'].dt.year.astype(int)
    df['release_month'] = df['release_date'].dt.month.astype(int)
    df['release_day'] = df['release_date'].dt.day.astype(int)

    # Drop columns
    df=df.drop(columns=['id', 'title', 'original_title', 'release_date'])

    return df

def feature_engineer(df):
    # Convert genre_ids from string to list if needed
    df['genre_ids']=df['genre_ids'].apply(
        lambda x: ast.literal_eval(x) if isinstance(x, str) else x
    )
    return df

df=preprocess_data(df)
df=feature_engineer(df)

In [4]:
df.head()

,overview,popularity,vote_average,vote_count,original_language,release_year,release_month,release_day,primary_genre
0,"On the rugged isle of Berk, where Vikings and ...",1075.8358,8.126,1013,en,2025,6,6,14
1,After the underlying tech for M3GAN is stolen ...,828.4871,7.711,376,en,2025,6,25,28
2,"Waking up in an unfamiliar city, a man with no...",510.3027,6.775,20,en,2025,1,13,28
3,"After a family tragedy, kung fu prodigy Li Fon...",368.2810,7.254,478,en,2025,5,8,28
4,"Superman, a journalist in Metropolis, embarks ...",359.1730,7.500,961,en,2025,7,9,878

In [5]:
numerical_cols=['popularity', 'vote_average', 'vote_count']
categorical_cols=['original_language', 'release_year', 'release_month', 'release_day']
textual_cols=['overview']

In [6]:
from scipy.stats import skew

print("[ BEFORE TRANSFORMATION ]")
for col in numerical_cols:
    print(f"Skewness[{col}]: {df[col].skew():.2f}")
    
def winsorize_series(series, lower_quantile=0.01, upper_quantile=0.99):
    lower = series.quantile(lower_quantile)
    upper = series.quantile(upper_quantile)
    return series.clip(lower, upper)

def transform(cols):
    for col in cols:
        skewness=df[col].skew()
        if skewness > 0.75: # log transform
            df[col]=np.log1p(df[col])
        elif skewness < -0.5: # reflect, then log transform
            df[col] = df[col].max() + 1 - df[col]
            df[col] = np.log1p(df[col])
        else: # sqrt transform
            df[col]=np.sqrt(df[col])

print("[ AFTER TRANSFORMATION ]")
df['popularity']=winsorize_series(df['popularity'])
transform(['popularity', 'vote_average', 'vote_count'])

for col in numerical_cols:
    print(f"Skewness[{col}]: {df[col].skew():.2f}")

[ BEFORE TRANSFORMATION ]
Skewness[popularity]: 42.32
Skewness[vote_average]: -1.09
Skewness[vote_count]: 5.18
[ AFTER TRANSFORMATION ]
Skewness[popularity]: 0.48
Skewness[vote_average]: 0.25
Skewness[vote_count]: -0.44

In [7]:
import matplotlib.pyplot as plt
import seaborn as sns

# corr_matrix=df.corr(numeric_only=True)
# plt.figure(figsize=(10, 7))
# sns.heatmap(corr_matrix, 
#             annot=True,          # Show correlation values
#             cmap='coolwarm',     # Color scheme (red-blue diverging)
#             vmin=-1, vmax=1,     # Correlation range
#             center=0,            # Center point for diverging colormap
#             square=True,         # Make cells square
#             fmt='.2f',           # Format numbers to 2 decimal places
#             annot_kws={'size': 10},  # Font size for annotations
#             linewidths=0.5)      # Lines between cells
# plt.title('Feature Correlation Heatmap')
# plt.show()

In [9]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV
from catboost import CatBoostClassifier, Pool

X=df.drop(columns=['genre_ids'])
y=df['genre_ids']

X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)

# Frequency Encoding for 'original_language'
freq_map = X_train['original_language'].value_counts().to_dict()
X_train['original_language_freq'] = X_train['original_language'].map(freq_map)
X_test['original_language_freq'] = X_test['original_language'].map(freq_map).fillna(0)

# Drop original 'language' col
X_train = X_train.drop(columns=['original_language'])
X_test = X_test.drop(columns=['original_language'])

# [ Setup for handling text columns for CatBoost ]
# Create Pool object for training
train_pool = Pool(X_train, y_train, text_features=textual_cols)
test_pool = Pool(X_test, y_test, text_features=textual_cols)

# [ Calculate for class weights ]
class_counts = y.value_counts() # Count each class
# Formula: total_samples / (num_classes * class_count)
total_samples = len(y)
n_classes = len(class_counts)
class_weights = {
    cls: total_samples / (n_classes * count)
    for cls, count in class_counts.items()
}

model=CatBoostClassifier(
    iterations=100,     # Moderate iterations
    depth=6,            # Balanced depth
    learning_rate=0.1,  # Standard learning rate
    l2_leaf_reg=3,      # Moderate regularization
    verbose=0,           # Suppress output
    class_weights=class_weights
)

model.fit(train_pool)
predictions=model.predict(test_pool)
accuracy=accuracy_score(y_test, predictions)

In [10]:
print(f"Accuracy: {accuracy:.2%}")

Accuracy: 31.54%